### ISSUE TITLE
Workshop registration

### ISSUE THREAD

**Issue by adswa** [adswa/mpi-datamanagement-ws#14]
When going virtual, we likely need to have participant register such that they can get an invitation with a zoom/jitsi/whatever link and a password.
I've created a Google doc for us to keep a list: https://docs.google.com/spreadsheets/d/16QTbtTF7UsQ2ZSY0vcZb8rfGdOxoTPw6xcaNtdTl9y8/edit#gid=0
@lnnrtwttkhn, you should have gotten an invitation to your institutional email, let me know if I should resend it.

**Comment by adswa** [comment]
I have created a custom e-mail address to which we both can get access: datamanagement.mpi@gmail.com
I'll send you the password via private message. I'll configure email forwarding from this account for myself.

**Comment by lnnrtwttkhn** [comment]
Great, thanks for setting up the email! We could also use Google Forms for the sign-up. This way we can gather information from the participants in a systematic way and we can set-up and automated confirmation e-mail that includes the link to the online platform that we will be using. What do you think?

**Comment by adswa** [comment]
We will switch from email registration to google forms (#16). We'll keep the email account for questions, but encourage question submission via GitHub issue.

**Comment by lnnrtwttkhn** [comment]
Google Forms is up (see #16) and I added a section to the Logistics section where to write questions to in 744818e.

I noticed two things:
1. We could add a GitHub issues template (though I don't think many people will interact with it potentially)
2. We should add more content to the FAQ soon (see separate issue #17)

otherwise we could close this, right? @adswa

**Comment by adswa** [comment]
>    We could add a GitHub issues template (though I don't think many people will interact with it potentially)
>    We should add more content to the FAQ soon (see separate issue #17)

agree to both! Will start with creating some templates, feel free to do so too or add, and close this issue.

**Comment by adswa** [comment]
Three issue templates done, feel free to add more!

**Comment by lnnrtwttkhn** [comment]
Looks perfect! Thank you very much! Didn't know that GitHub is actually rendering the templates in a multiple-choice menu. cool!
