### ISSUE TITLE
offer multiple days for workshop

### ISSUE THREAD

**Issue by lnnrtwttkhn** [adswa/mpi-datamanagement-ws#18]
hey @adswa, I know that we already settled for a date but I wondered if it would be a good idea to offer multiple dates (e.g., three to five) and then let everyone indicate their preferred dates during the registration?

given that we are rather flexible with the exact day, this might allow us to maximize the number of potential participants? the question about the dates could easily be included in the registration. what do you think?

**Comment by adswa** [comment]
That's a generous idea, but I wouldn't go down this rabbit hole - we would need to create a doodle, send out the doodle, pick a date for everyone to respond by, and communicate the date again - that's a lot of overhead in administration effort for us and potential attendees. I would at most ask people you consider relevant in private about date preferences, settle on a date, and then send this out. If done early enough, everyone who wants to attend has a chance to adjust their schedule. And even if not, we'll record everything so it is available also to the ones that want to attend but can't.

**Comment by lnnrtwttkhn** [comment]
Ok, agreed, Closing again.
